We/ditto heartbeat
getditto/DittoCSharpTools pull request #1
Opened 2024-05-03 20:16 UTC by texasRanger09

2024-05-03 20:27 UTC, bplattenburg requested changes

2024-05-03 20:27 UTC, bplattenburg commented on DittoHeartbeat/Class1.cs
> +﻿using DittoSDK;
nit: should we rename this file to something meaningful?

2024-05-03 20:27 UTC, bplattenburg commented on DittoHeartbeat/Class1.cs
> +                { "metaData", metaData },
I _think_ this should be all lowercase `metadata` to match the other platforms?

2024-05-03 20:27 UTC, bplattenburg commented on DittoHeartbeat/DittoHeartbeat.csproj
> +    <PackageReference Include="Ditto" Version="4.7.1" />
I admittedly don't know the syntax here, but can we make this work with a minimum version instead of an exact match? e.g. ">= 4.7.0"

2024-05-06 18:06 UTC, rajramsaroop requested changes

2024-05-06 18:06 UTC, rajramsaroop commented on DittoToolsApp/Program.cs
> +            ditto = new Ditto(identity: DittoIdentity.OnlinePlayground("ef7f7d95-81ba-44f6-bdfe-eb74ee57d520", "b3328d7b-1098-4bd2-91ed-2c464a1f9a6d"));
Did you mean to make these values public?

2024-05-06 18:07 UTC, texasRanger09 commented on DittoToolsApp/Program.cs
> +            ditto = new Ditto(identity: DittoIdentity.OnlinePlayground("ef7f7d95-81ba-44f6-bdfe-eb74ee57d520", "b3328d7b-1098-4bd2-91ed-2c464a1f9a6d"));
Fixing this and removing the ditto folder that got added well

2024-05-06 18:08 UTC, rajramsaroop commented
Add a README for project setup/secrets etc

2024-05-06 19:21 UTC, texasRanger09 commented
@rajramsaroop I added a temp README. The readme will need to be updated as we add the heartbeat and other tools to the nuget package manager, but this temp readme will allow you to run the app for now.

2024-05-06 20:23 UTC, bplattenburg commented
I went ahead and broke out the custom health metrics into another issue similar to what we did in DittoAndroidTools and DittoSwiftTools: https://github.com/getditto/DittoCSharpTools/issues/2

2024-05-07 14:54 UTC, bplattenburg approved these changes

2024-05-07 18:34 UTC, rajramsaroop approved these changes

2024-05-08 15:22 UTC, merged